package com.hywl.cck.shiro.entity;

import java.util.Date;

public class SysRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_sn
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    private String roleSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_status
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    private String roleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.remarks
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.create_time
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.modify_time
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.create_by
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    private String createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_sn
     *
     * @return the value of sys_role.role_sn
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public String getRoleSn() {
        return roleSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_sn
     *
     * @param roleSn the value for sys_role.role_sn
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public void setRoleSn(String roleSn) {
        this.roleSn = roleSn == null ? null : roleSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_name
     *
     * @return the value of sys_role.role_name
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_name
     *
     * @param roleName the value for sys_role.role_name
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_status
     *
     * @return the value of sys_role.role_status
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public String getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_status
     *
     * @param roleStatus the value for sys_role.role_status
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public void setRoleStatus(String roleStatus) {
        this.roleStatus = roleStatus == null ? null : roleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.remarks
     *
     * @return the value of sys_role.remarks
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.remarks
     *
     * @param remarks the value for sys_role.remarks
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.create_time
     *
     * @return the value of sys_role.create_time
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.create_time
     *
     * @param createTime the value for sys_role.create_time
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.modify_time
     *
     * @return the value of sys_role.modify_time
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.modify_time
     *
     * @param modifyTime the value for sys_role.modify_time
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.create_by
     *
     * @return the value of sys_role.create_by
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.create_by
     *
     * @param createBy the value for sys_role.create_by
     *
     * @mbg.generated Wed May 23 13:50:17 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }
}